config/routes.rb
Spree::Core::Engine.routes.draw do
  namespace :admin do
    resources :galleries do
      collection do
        post :upload_items
      end
    end
  end

  namespace :api, defaults: {format: 'json'} do
    namespace :v1 do
      resources :gallery_items do
        collection do
          post :classify
          put :sort
          delete :remove
        end
      end

      get '/galleries/products', to: 'galleries#products', as: :gallery_products
    end
  end
end

app/models/spree/gallery.rb
class Spree::Gallery < ActiveRecord::Base
  extend FriendlyId

  has_many :gallery_items, -> { order(:position) }, class_name: 'GalleryItem', dependent: :delete_all, inverse_of: :gallery
  has_many :products, through: :gallery_items
  belongs_to :store

  friendly_id :title, use: :slugged

  validates :name, presence: true
  validates :title, presence: true

  scope :published, -> { where(published: true) }
  scope :by_store, ->(store) { where(store_id: store) }
end

app/models/spree/gallery_item.rb
class Spree::GalleryItem < ActiveRecord::Base
  belongs_to :gallery, class_name: 'Spree::Gallery'
  belongs_to :product, class_name: 'Spree::Product'
  acts_as_list scope: :gallery

  validates :gallery, :product, presence: true
  validates_uniqueness_of :product_id, scope: [:gallery_id]
end

app/models/spree/product_decorator.rb
Spree::Product.class_eval do
  has_many :gallery_items, class_name: 'GalleryItem', dependent: :delete_all, inverse_of: :product
  has_many :galleries, through: :gallery_items
end

app/controllers/spree/admin/galleries_controller.rb
module Spree
  module Admin
    class GalleriesController < ResourceController
      def find_resource
        Spree::Gallery.friendly.find(params[:id])
      end

      def upload_items
        @gallery = Spree::Gallery.friendly.find(params[:id])
        begin
          file = params[:upload_file]
          products_not_found = 0
          products_existing = 0
          products_added = 0
          CSV.foreach(file.path, headers: false) do |row|
            product = Spree::Product.find_by(name: row[0])
            if product.blank?
              products_not_found += 1
              next
            end
            if @gallery.products.include?(product)
              products_existing += 1
            else
              @gallery.products << product
              products_added += 1
            end
          end
          flash[:notice] = t('spree_gallery.upload_results', {added: products_added, existing: products_existing, not_found: products_not_found})
        rescue
          flash[:error] = t('spree_gallery.upload_error')
        ensure
          redirect_to edit_admin_gallery_path(@gallery)
        end
      end
    end
  end
end

app/controllers/spree/api/v1/galleries_controller.rb
module Spree
  module Api
    module V1
      class GalleriesController < Spree::Api::BaseController
        def products
          # Returns the products sorted by their position in gallery
          gallery = Spree::Gallery.find(params[:id])
          @products = gallery.products.ransack(params[:q]).result
          @products = @products.page(params[:page]).per(params[:per_page] || 50)
          render 'spree/api/v1/products/index'
        end
      end
    end
  end
end

app/controllers/spree/api/v1/gallery_items_controller.rb
module Spree
  module Api
    module V1
      class GalleryItemsController < Spree::Api::BaseController
        before_action :find_product
        before_action :find_gallery

        def classify
          authorize! :create, GalleryItem
          @gallery_item = Spree::GalleryItem.new({ gallery: @gallery, product: @product })
          if @gallery_item.save
            respond_with(@gallery_item, status: 200, default_template: :show)
          else
            invalid_resource!(@gallery_item)
          end
        end

        def sort
          authorize! :update, GalleryItem
          gallery_item = Spree::GalleryItem.find_by(gallery: @gallery, product: @product)
          # Because position we get back is 0-indexed.
          # acts_as_list is 1-indexed.
          gallery_item.insert_at(params[:position].to_i + 1)
          head :ok
        end

        def remove
          gallery_item = Spree::GalleryItem.find_by(gallery_id: params[:gallery_id], product_id: params[:product_id])
          gallery_item.destroy if gallery_item.present?
          head :no_content
        end

        private

        def find_product
          @product = super(params[:product_id])
          authorize! :read, @product
        end

        def find_gallery
          @gallery ||= Spree::Gallery.accessible_by(current_ability, :read).find(params[:gallery_id])
        end
      end
    end
  end
end

app/views/spree/admin/galleries/_assets.html.erb
<script>
    Spree.assets_noimage_small = '<%= image_path('noimage/small.png') %>';
</script>

app/views/spree/admin/galleries/_form.html.erb
<div data-hook="admin_gallery_form_fields" class="row">
  <div class="col-xs-12 col-md-6">
    <%= f.field_container :name, class: ['form-group'] do %>
        <%= f.label :name, Spree.t(:name) %> <span class="required">*</span>
        <%= f.text_field :name, class: "form-control" %>
        <%= f.error_message_on :name %>
    <% end %>
  </div>
  <div class="col-xs-12 col-md-6">
    <%= f.field_container :title, class: ['form-group'] do %>
        <%= f.label :title, Spree.t(:title) %> <span class="required">*</span>
        <%= f.text_field :title, class: "form-control" %>
        <%= f.error_message_on :title %>
    <% end %>
  </div>
  <div class="col-xs-12 col-md-6">
    <%= f.field_container :description, class: ['form-group'] do %>
        <%= f.label :description, Spree.t(:description) %>
        <%= f.text_field :description, class: "form-control" %>
        <%= f.error_message_on :description %>
    <% end %>
  </div>
  <div class="col-xs-12 col-md-3">
    <%= f.field_container :store_id, class: ['form-group'] do %>
      <%= f.label :name, Spree.t(:store) %> <span class="required">*</span>
      <%= f.collection_select(:store_id, Spree::Store.all, :id, :name, { include_blank: Spree.t('match_choices.none') }, { class: 'select2' }) %>
    <% end %>
  </div>
  <div class="col-xs-12 col-md-3">
    <%= f.field_container :published, class: ['form-group'] do %>
      <div class="checkbox">
        <label>
          <%= f.check_box :published %>
          <%= t('spree_gallery.published') %>
        </label>
      </div>
    <% end %>
  </div>
</div>

app/views/spree/admin/galleries/_routes.html.erb
<script>
    Spree.routes.remove_api_v1_gallery_items_path = "<%= spree.remove_api_v1_gallery_items_path %>";
</script>

app/views/spree/admin/galleries/_translations.html.erb
<script>
    Spree.translations.delete_from_gallery = '<%= t('spree_gallery.delete_from_gallery') %>';
</script>

app/views/spree/admin/galleries/edit.html.erb
<% content_for :page_title do %>
    <%= link_to t('spree_gallery.title'), spree.admin_galleries_url %> /
    <%= @gallery.name %>
<% end %>

<% content_for :page_actions do %>
    <%= button_link_to t('spree_gallery.back_to_galleries'), spree.admin_galleries_path, icon: 'arrow-left' %>
<% end %>

<%= render partial: 'spree/admin/shared/error_messages', locals: {target: @gallery} %>

<%= form_for [:admin, @gallery] do |f| %>
    <div class="panel panel-default">
      <div class="panel-heading">
        <h1 class="panel-title">
          <%= t('spree_gallery.attributes') %>
        </h1>
      </div>
      <div class="panel-body">
        <%= render partial: 'form', locals: {f: f} %>
      </div>
      <div class="panel-footer text-center">
        <%= render partial: 'spree/admin/shared/edit_resource_links' %>
      </div>
    </div>
<% end %>

<div class="panel panel-default">
  <div class="panel-heading">
    <h1 class="panel-title">
      <%= t('spree_gallery.upload_items_title') %> (CSV)
    </h1>
  </div>
  <div class="panel-body">
    <div class="row">
      <div class="col-md-12">
        <%= form_tag upload_items_admin_galleries_path, {multipart: true, class: 'form-inline'} do %>
            <%= hidden_field_tag :id, @gallery.id %>
            <div class="form-group">
              <%= file_field_tag :upload_file, required: true, accept: 'text/csv' %>
            </div>
            <%= submit_tag t('spree_gallery.upload_items_action'), class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-6">
    <%= text_field_tag 'search_product' %>
  </div>
  <div class="col-md-6">
    <%= button_link_to t('spree_gallery.add_item'), "javascript:;", {
        icon: 'add',
        id: 'add_product',
        class: 'btn-success',
        'data-route': classify_api_v1_gallery_items_path
    }
    %>
  </div>
</div>

<div class="gallery-products-view">
  <div class="form-group">
    <%= hidden_field :gallery, :id %>
  </div>

  <ul id="gallery_products" class="gallery" data-items-route="<%= sort_api_v1_gallery_items_path %>" data-products-route="<%= api_v1_gallery_products_path %>"></ul>

  <%= render partial: "spree/admin/galleries/translations" %>
  <%= render partial: "spree/admin/galleries/assets" %>
  <%= render partial: "spree/admin/galleries/routes" %>
</div>

app/views/spree/admin/galleries/index.html.erb
<% content_for :page_title do %>
    <%= t('spree_gallery.title') %>
<% end %>

<% content_for :page_actions do %>
    <%= button_link_to t('spree_gallery.new_gallery'), new_object_url, {class: 'btn-success', icon: 'add', id: 'admin_new_gallery_link'} %>
<% end %>

<% if @galleries.any? %>
    <table class="table" id="listing_galleries" data-hook>
      <thead>
      <tr data-hook="admin_galleries_index_headers">
        <th><%= Spree.t(:name) %></th>
        <th><%= Spree.t(:store) %></th>
        <th data-hook="admin_galleries_index_header_actions" class="actions"></th>
      </tr>
      </thead>
      <tbody>
      <% @galleries.each do |gallery| %>
          <tr>
            <td class="presentation"><%= gallery.name %></td>
            <td class="presentation">
              <%= gallery.store.name if gallery.store%>
            </td>
            <td data-hook="admin_galleries_index_row_actions" class="actions actions-2 text-right">
              <%= link_to_edit gallery, no_text: true, class: 'edit' %>
              <%= link_to_delete gallery, no_text: true %>
            </td>
          </tr>
      <% end %>
      </tbody>
    </table>
<% else %>
    <div class="alert alert-info no-objects-found">
      <%= Spree.t(:no_resource_found, resource: plural_resource_name(Spree::Gallery)) %>,
      <%= link_to Spree.t(:add_one), new_object_url if can?(:create, Spree::Gallery) %>!
    </div>
<% end %>

app/views/spree/admin/galleries/new.html.erb
<% content_for :page_title do %>
    <%= link_to t('spree_gallery.title'), spree.admin_galleries_url %> /
  <%= t('spree_gallery.new_gallery') %>
<% end %>

<% content_for :page_actions do %>
  <%= button_link_to t('spree_gallery.back_to_galleries'), spree.admin_galleries_path, icon: 'arrow-left' %>
<% end %>

<%= render 'spree/shared/error_messages', target: @gallery %>

<%= form_for [:admin, @gallery] do |f| %>
  <fieldset>
    <%= render partial: 'form', locals: { f: f } %>
    <%= render partial: 'spree/admin/shared/new_resource_links' %>
  </fieldset>
<% end %>